# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FABYPr57rgBprBpAM0gCQ9pI1qSKV3j6
"""

import pandas as pd
import matplotlib.pyplot as plt

# Create the dataset directly
df = pd.DataFrame({
    "Date": [
        "2026-01-01", "2026-01-02", "2026-01-03", "2026-01-04", "2026-01-05",
        "2026-01-06", "2026-01-07", "2026-01-08", "2026-01-09", "2026-01-10"
    ],
    "Category": [
        "Electronics", "Clothing", "Furniture", "Electronics", "Groceries",
        "Clothing", "Furniture", "Electronics", "Groceries", "Clothing"
    ],
    "Sales": [1200, 800, 1500, 1800, 600, 950, 1700, 2100, 700, 1100]
})

# Display data
print(df.head())
print(df.describe())

# Bar chart
df["Category"].value_counts().plot(kind="bar")
plt.title("Category Distribution")
plt.xlabel("Category")
plt.ylabel("Count")
plt.show()